kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
  encryptedData:
    postgresql-password: AgCdvKgYyDVrXaZrzUt7FRDP8JOx5/ddZTYRQK6s1Zmi+FTpldBZpOhRuZhFsYthpMAK/jQPu7MKuxLLErdkmBFOgCWQL0GeW9us3E/f482+fHxFtlmNqVhlG3xRWPXp9T/J2xFos2egfXf9hlPRd/J2rBTeV8+EmUO0fGf5LOBRFMFi1vH4CzoS5PefNrxrmgZjL8G5/DzWzksSTf4dMPf8djtc0l/af2c+M18f28jx5xnZD7j4+aPHOsULoEit+r40BvjDuaDwHDfaWw62SxCGRvD1GXKEu3tSxBKSRjIwK+YoIntMdQPrfPXkbHTGAKUw6GGkDN+zv9Y5bzQrvbzAVjhYrPCKKH8f5GVdPTERWHszrc+cLB/EPAgePGpdGJ7AufKVvz0xR6V8ectvTGe6mdTfwK/EcRAkD+0QUdYT/rK+pqTxayad7fxbeTO6wODRzo2ZxfLkvdpKY2xaauzA2qQpRpJDqrA+N4UyccU5zT2e35Wc0yB403dEhVGZgCPbv+O0dV7PSpdQLZXQrcyL4OMOqd6Fv0dT6P0GXpHPdQggxps+lH8DDPTsz8SFUR7F6GslLB1P183QNxuA78Euh5p1cC3NysaBZKU1L4sGLpLkCe4/a9qaRS4CaMzttqWciYzUnju0QRACJy0wfSuhFpOOyf6ZrPE2a4LHKqgxopMmw1Hy0v2mOE4arA7n1ScmZyycecXFq5RkqRNmZX9DyW+VtevOpbzkqCEXklXb2Q==
    postgresql-postgres-password: AgCge9phJ0J7pTOJVTKUhInUAlugIUcSXuebgyIrnvwbhIGCODd6bNJ2ASU7Uu9QrKuVAi+Ck80+QwBJr9SBsOE6GWNQQcTH3ocj3TIpMs4Y8wvaA9Qq1yLwSm222osZ70RvPRSg0b5dG3H98PPvxK5xONu27qRUN4X2mwuzrTYOW6ap+FJpA/tKRBhg3DqmTVHt+tylnEO413g9Z78CeZhIoa68AGxxXC94wGAJOUyYL8MrC2aQeipYzK0apKm27/ylsJXGoleoDPeEml4+XTXmUWKrGkDkJ4e9Ugz9T8l8txIjh9s3CFDTpRNiqvg2peJjynz0PPuboXt6RNb+doEvWWMcM9i/lJEWz1qngGntxg77syMxO5FUOUFlIBPq0DAnMr0j0IGITRyXDTDrHhCEEl4jngOEQf8f7fgrb+osYyeTkX8s7uuwLGEXRWFUqYrTjgMkgaugRzWYBb5T2/+n64wK3KUHfKsxQzqO70wkZzoo2h1Mo+4zdNZ7BmXjOtuoMQz0hiyFUhjIHRr3mfMjuuWUDAnELjOoMtgb8NtcDFut00oYKak+ie4LUWfaVYsmrJoUXUpc/eeZtN9g9GXbdtnErmY/niTg50xaWKHi5UyQsxwDL8VzMxedOUTYwJT+aQ/lc4FGPoweNHwutsDnqG637pfvImyjpO3zsv6B/Dob767x12GnO4PlBtoRaCFAXXSwZDrYbMcga4k/Wj6oO8R81vN6ydbmDMCSQU4sVQ==
